---
config:
  - name: number_of_fruits
    description: The number of fruits we have.
    type: gauge
    labels: [name, color]
    sequence:
      - time: 5
        values: 0-20
        operation: inc
      - eval_time: 5
        labels:
          name: apple
          color: red
      - time: 5
        eval_time: 1
        values: 0-20
        operation: inc
        labels:
          name: apple
          color: green
      - time: 5
        eval_time: 1
        values: 0-5
        operation: dec
        labels:
          name: apple
          color: green
      - time: 5
        eval_time: 1
        value: 3
        operation: inc
        labels:
          name: apple
          color: yellow
