---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-data-generator
  name: prometheus-data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-data-generator
  template:
    metadata:
      labels:
        app: prometheus-data-generator
    spec:
      containers:
      - image: littleangryclouds/prometheus-data-generator:0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: PDG_CONFIG
          value: /pdg/config.yml
        name: prometheus-data-generator
        ports:
        - containerPort: 9000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /pdg/
      - image: quay.io/coreos/configmap-reload:v0.0.1
        args:
        - -webhook-url=http://localhost:9000/-/reload
        - -volume-dir=/pdg/
        - -webhook-method=GET
        name: config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
          requests:
            cpu: 5m
            memory: 10Mi
        volumeMounts:
        - name: config
          mountPath: /pdg/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: prometheus-data-generator
