---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-data-generator
    prometheus: kube-prometheus
    # this label is needed in case of using default kube-prometheus-stack helm chart
    # so that prometheus picks this up
    app.kubernetes.io/managed-by: Helm
  name: prometheus-data-generator
spec:
  endpoints:
  - interval: 10s
    path: /metrics/
    port: metrics
  selector:
    matchLabels:
      app: prometheus-data-generator
